vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO cosmoscout/vista
    REF 6c3806f6e95dcb3d23d35e3f1be7c8c8524fe3eb
    SHA512 231cf4c27034877575f921c62b4586497eaeff901280aef18b8aeebc8806a31d44f798c98ecd042965018dc05b3717ec98bf8cf53c4552a2b12dc98544e3560b
    HEAD_REF feature/vcpkg
)

set(VISTA_WINDOW_SDL2_FEATURE Off)
if ("window-sdl2" IN_LIST FEATURES)
  set(VISTA_WINDOW_SDL2_FEATURE On)
endif ()

set(VISTA_WINDOW_GLUT_FEATURE Off)
if ("window-glut" IN_LIST FEATURES)
  set(VISTA_WINDOW_GLUT_FEATURE On)
endif ()

set(VISTA_OPENVR_FEATURE Off)
if ("openvr" IN_LIST FEATURES)
  set(VISTA_OPENVR_FEATURE On)
endif ()

set(VISTA_NETWORKING_ZMQ_FEATURE Off)
if ("networking-zmq" IN_LIST FEATURES)
  set(VISTA_NETWORKING_ZMQ_FEATURE On)
endif ()

set(VISTA_DRIVER_OPENAL_RECORD_FEATURE Off)
if ("driver-openal-record" IN_LIST FEATURES)
  set(VISTA_DRIVER_OPENAL_RECORD_FEATURE On)
endif ()

set(VISTA_DRIVER_OPENCV_CAPTURE_FEATURE Off)
if ("driver-opencv-capture" IN_LIST FEATURES)
  set(VISTA_DRIVER_OPENCV_CAPTURE_FEATURE On)
endif ()

set(VISTA_DRIVER_OPENCV_FACE_TRACK_FEATURE Off)
if ("driver-opencv-face-track" IN_LIST FEATURES)
  set(VISTA_DRIVER_OPENCV_FACE_TRACK_FEATURE On)
endif ()

set(VISTA_DRIVER_OPENNI_FEATURE Off)
if ("driver-openni" IN_LIST FEATURES)
  set(VISTA_DRIVER_OPENNI_FEATURE On)
endif ()

set(VISTA_DRIVER_WIIMOTE_FEATURE Off)
if ("driver-wiimote" IN_LIST FEATURES)
  set(VISTA_DRIVER_WIIMOTE_FEATURE On)
endif ()

set(VISTA_DRIVER_DIRECTX_GAMEPAD_FEATURE Off)
if ("driver-directx-gamepad" IN_LIST FEATURES)
  set(VISTA_DRIVER_DIRECTX_GAMEPAD_FEATURE On)
endif ()

vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    -DVISTA_DEMO=Off
    -DVISTA_TESTS=Off
    -DVISTA_CORELIBS_USE_SDL2_WINDOWIMP=${VISTA_WINDOW_SDL2_FEATURE}
    -DVISTA_CORELIBS_USE_GLUT_WINDOWIMP=${VISTA_WINDOW_GLUT_FEATURE}
    -DVISTA_CORELIBS_USE_OPENVR=${VISTA_OPENVR_FEATURE}
    -DVISTA_CORELIBS_USE_ZEROMQ=${VISTA_NETWORKING_ZMQ_FEATURE}
    -DVISTA_DRIVERS_OPENVR=${VISTA_OPENVR_FEATURE}
    -DVISTA_DRIVERS_OPENALRECORD=${VISTA_DRIVER_OPENAL_RECORD_FEATURE}
    -DVISTA_DRIVERS_OPENCVCAPTURE=${VISTA_DRIVER_OPENCV_CAPTURE_FEATURE}
    -DVISTA_DRIVERS_OPENCVFACETRACK=${VISTA_DRIVER_OPENCV_FACE_TRACK_FEATURE}
    -DVISTA_DRIVERS_OPENNI=${VISTA_DRIVER_OPENNI_FEATURE}
    -DVISTA_DRIVERS_WIIMOTE=${VISTA_DRIVER_WIIMOTE_FEATURE}
    -DVISTA_DRIVERS_DIRECTXGAMEPAD=${VISTA_DRIVER_DIRECTX_GAMEPAD_FEATURE}
    -DVISTA_CORELIBS_USE_INFINITE_REVERSE_PROJECTION=On
    -DVISTA_USE_PRECOMPILED_HEADERS=On
    -DCMAKE_UNITY_BUILD=On
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
# vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
#
# file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
# file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
# file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")