name: Continuous Integration

on: [push]

jobs:
  clang_format:
    name: Check Clang-Format
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Download Clang-Format
      run: |
        sudo apt-get update -y
        sudo apt-get remove -y clang-6.0 libclang-common-6.0-dev libclang1-6.0 libllvm6.0
        sudo apt-get autoremove
        sudo apt-get install -y clang-format
    - name: Run Clang-Format
      run: ./clang-format.sh
    - name: Compare Results
      run: |
        DIFF=$(git diff)
        if [ ! -z "$DIFF" ]; then echo $DIFF && exit 1; fi
        
  build_linux_gcc:
    name: Linux Build (gcc)
    runs-on: ubuntu-18.04
    needs: clang_format
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Download Dependencies
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update -q
        sudo apt-get install libc++-dev
        sudo apt-get install libgl1-mesa-dev
        sudo apt-get install libglu1-mesa-dev
        sudo apt-get install libx11-dev
        sudo apt-get install libxi-dev
        sudo apt-get install libgconf-2-4
        sudo apt-get install libboost1.70-dev
    - name: Build Externals
      run: ./make_externals.sh
    - name: Build CosmoScout VR
      run: ./make.sh
      
  build_linux_clang:
    name: Linux Build (clang)
    runs-on: ubuntu-18.04
    needs: clang_format
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Download Dependencies
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update -q
        sudo apt-get install libc++-dev
        sudo apt-get install libgl1-mesa-dev
        sudo apt-get install libglu1-mesa-dev
        sudo apt-get install libx11-dev
        sudo apt-get install libxi-dev
        sudo apt-get install libgconf-2-4
        sudo apt-get install libboost1.70-dev
        export CC=clang
        export CXX=clang++
    - name: Build Externals
      run: ./make_externals.sh
    - name: Build CosmoScout VR
      run: ./make.sh

  build_windows:
    name: Windows Build
    runs-on: windows-2016
    needs: clang_format
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Build Externals
      run: ./make_externals.bat
    - name: Build CosmoScout VR
      run: ./make.bat
