name: Compile Releases

on: [push]

jobs:
  source_code:
    name: Source Code
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Create Archive
      run: externals/git-archive-all.sh/git-archive-all.sh --prefix cosmoscout-vr/ source-with-submodules.tar.gz
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: source-with-submodules
        path: source-with-submodules.tar.gz
        
  release_linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Download Dependencies
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update -q
        sudo apt-get install libc++-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev
        sudo apt-get install libxi-dev libgconf-2-4 libboost1.70-dev
    - name: Get Example Data
      run: ./get_example_data.sh
    - name: Build Externals
      run: ./make_externals.sh
    - name: Build CosmoScout VR
      run: ./make.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: cosmoscout-vr-linux64
        path: install/linux-release

  release_windows:
    name: Windows
    runs-on: windows-2016
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Get Example Data
      run: ./get_example_data.bat
    - name: Build Externals
      run: ./make_externals.bat
    - name: Build CosmoScout VR
      run: ./make.bat
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: cosmoscout-vr-win64
        path: install/windows-release
